### ISSUE TITLE
Compliance scanning capabilities

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#1013]
As as user, I would like to be able to use compliance scanners to provide additional security visibility into my assets. VMClarity should be capable of discovering scannable assets and then scanning them using an agent-less mechanism to ensure there is no impact to the source. CIS Docker Benchmark scanner should be migrated from KubeClarity and repurposed as a compliance scanner to reduce implementation steps.

Tasks:
- [ ] #987
- [ ] Add API models and boilerplate for compliance scanning
- [ ] Extend UI to support compliance findings
- [ ] Migrate CIS Docker Benchmark from KubeClarity as a compliance scanner
